import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'

const rootDir = dirname(fileURLToPath(import.meta.url))

const API_TARGET = process.env.FASTWORK_API_TARGET || 'http://127.0.0.1:8000'

// A single public tunnel (cloudflared/ngrok) can expose the app AND the API: the
// app calls /api/* on its own origin and Vite forwards it to the local FastAPI.
// One HTTPS origin means no mixed content, no CORS dance, and the service worker
// + install prompt keep working from a phone on a different network.
const apiProxy = {
  '/api': {
    target: API_TARGET,
    changeOrigin: true,
    rewrite: (path) => path.replace(/^\/api/, ''),
  },
}

// Hostnames a public tunnel may use. Vite rejects unknown Host headers, so the
// tunnel domains (and any custom one from FASTWORK_ALLOWED_HOSTS) are allowed.
const TUNNEL_HOSTS = [
  '.trycloudflare.com',
  '.ngrok-free.app',
  '.ngrok-free.dev',
  '.ngrok.app',
  '.ngrok.io',
  '.lhr.life',
  '.localtunnel.me',
  '.localhost.run',
  // Tailscale Serve/Funnel: https://<nama-pc>.<tailnet>.ts.net
  '.ts.net',
]

const extraHosts = (process.env.FASTWORK_ALLOWED_HOSTS || '')
  .split(',')
  .map((host) => host.trim())
  .filter(Boolean)

// HTTPS is opt-in: set FASTWORK_HTTPS=1 (start-mobile-https.bat does it) and the
// self-signed pair generated by scripts/make_dev_cert.py is used. Plain HTTP is
// the default so the app also works on a phone over a normal Wi-Fi connection.
function tlsConfig() {
  if (process.env.FASTWORK_HTTPS !== '1') return undefined
  const key = resolve(rootDir, 'certs/dev-key.pem')
  const cert = resolve(rootDir, 'certs/dev-cert.pem')
  if (!existsSync(key) || !existsSync(cert)) {
    throw new Error(
      'FASTWORK_HTTPS=1 but certs/dev-key.pem / certs/dev-cert.pem are missing. ' +
        'Run: python frontend-react/scripts/make_dev_cert.py',
    )
  }
  return { key: readFileSync(key), cert: readFileSync(cert) }
}

const https = tlsConfig()

// https://vite.dev/config/
export default defineConfig({
  base: process.env.GITHUB_PAGES === 'true' ? '/ProjekAyah/' : './',
  plugins: [react()],
  // host: true → listen on 0.0.0.0 so a phone on the same Wi-Fi can open the app
  // at http://<pc-lan-ip>:<port> (and install it as a PWA once the origin is trusted).
  server: {
    host: true,
    port: 5173,
    https,
    allowedHosts: ['.localhost', 'localhost', '127.0.0.1', ...TUNNEL_HOSTS, ...extraHosts],
    proxy: apiProxy,
  },
  preview: {
    host: true,
    port: 4173,
    https,
    strictPort: true,
    proxy: apiProxy,
  },
  build: {
    target: 'es2020',
    sourcemap: false,
  },
})
